{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg", "title": "A Light in the Attic", "price": "51.77", "availability": true, "rating": 3}
{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg", "title": "Tipping the Velvet", "price": "53.74", "availability": true, "rating": 1}
{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/soumission_998/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg", "title": "Soumission", "price": "50.10", "availability": true, "rating": 1}
{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/sharp-objects_997/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg", "title": "Sharp Objects", "price": "47.82", "availability": true, "rating": 4}
{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg", "title": "Sapiens: A Brief History of Humankind", "price": "54.23", "availability": true, "rating": 5}
{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/the-requiem-red_995/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg", "title": "The Requiem Red", "price": "22.65", "availability": true, "rating": 1}
{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg", "title": "The Dirty Little Secrets of Getting Your Dream Job", "price": "33.34", "availability": true, "rating": 4}
{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg", "title": "The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull", "price": "17.93", "availability": true, "rating": 3}
{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg", "title": "The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics", "price": "22.60", "availability": true, "rating": 4}
{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/the-black-maria_991/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/58/46/5846057e28022268153beff6d352b06c.jpg", "title": "The Black Maria", "price": "52.15", "availability": true, "rating": 1}
{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg", "title": "Starving Hearts (Triangular Trade Trilogy, #1)", "price": "13.99", "availability": true, "rating": 2}
{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg", "title": "Shakespeare's Sonnets", "price": "20.66", "availability": true, "rating": 4}
{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/set-me-free_988/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg", "title": "Set Me Free", "price": "17.46", "availability": true, "rating": 5}
{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg", "title": "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", "price": "52.29", "availability": true, "rating": 5}
{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg", "title": "Rip it Up and Start Again", "price": "35.02", "availability": true, "rating": 5}
{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg", "title": "Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991", "price": "57.25", "availability": true, "rating": 3}
{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/olio_984/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg", "title": "Olio", "price": "23.88", "availability": true, "rating": 1}
{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg", "title": "Mesaerion: The Best Science Fiction Stories 1800-1849", "price": "37.59", "availability": true, "rating": 1}
{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg", "title": "Libertarianism for Beginners", "price": "51.33", "availability": true, "rating": 2}
{"list_url": "https://books.toscrape.com/", "book_url": "https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html", "thumbnail_url": "https://books.toscrape.com/media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg", "title": "It's Only the Himalayas", "price": "45.17", "availability": true, "rating": 2}
